version: "3"
services:
  # Customized geth image for indexer
  geth:
    image: quay.io/amis/geth:indexer_diff_1.8.10
    ports:
      - "30303:30303"
      - "8546:8546"
    volumes:
      - ${GETH_DATA_PATH}:/root/.ethereum
    command: "--gcmode=archive --syncmode=full --wsapi \"eth,debug\" --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins \"*\""
    restart: always
    depends_on:
      - ws-database
  ws-database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_CHARSET=utf8
      - MYSQL_DATABASE=eth-db
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
  ws-migration:
    build:
      context: ./migration
    command: ["rake", "db:migrate"]
    restart: on-failure
    depends_on:
      - ws-database
    environment:
      - RAILS_ENV=customized
      - HOST=ws-database
      - PORT=3306
      - DATABASE=eth-db
      - USERNAME=root
      - PASSWORD=my-secret-pw
  ws-indexer:
    build:
      context: .
      dockerfile: ./cmd/service/Dockerfile
    command:
      - indexer
      - ws-database
      - geth
    restart: on-failure
    depends_on:
      - ws-database
      - ws-migration
      - geth
